# Generated by Django 5.0.2 on 2024-11-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('url', models.URLField(verbose_name='Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('title_en_us', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('title_uz_Latn', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('title_uz_Cyrl', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botToken', models.CharField(max_length=255, verbose_name='Telegram Token')),
                ('channel_id', models.CharField(max_length=255, verbose_name='Channel')),
                ('is_test_mode', models.BooleanField(default=False, verbose_name='Test mode')),
                ('test_mode_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Test mode info')),
                ('test_mode_info_en_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='Test mode info')),
                ('test_mode_info_uz_Latn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Test mode info')),
                ('test_mode_info_uz_Cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Test mode info')),
                ('test_mode_info_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Test mode info')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone Number')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domen')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_en_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_uz_Latn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_uz_Cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('name_en_us', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_uz_Latn', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_uz_Cyrl', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Joy',
                'verbose_name_plural': 'Joylar',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('first_name_en_us', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('first_name_uz_Latn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('first_name_uz_Cyrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('first_name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familya')),
                ('last_name_en_us', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familya')),
                ('last_name_uz_Latn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familya')),
                ('last_name_uz_Cyrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familya')),
                ('last_name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familya')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Rasm')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('position_en_us', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('position_uz_Latn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('position_uz_Cyrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('position_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('licence_no', models.SmallIntegerField(blank=True, null=True, verbose_name='Guvohnoma raqami')),
            ],
            options={
                'verbose_name': 'Hodim ',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Rasm')),
                ('intro', models.TextField(verbose_name='Kirish matni')),
                ('intro_en_us', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Latn', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Cyrl', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_ru', models.TextField(null=True, verbose_name='Kirish matni')),
                ('content', models.TextField(verbose_name='Batafsil')),
                ('content_en_us', models.TextField(null=True, verbose_name='Batafsil')),
                ('content_uz_Latn', models.TextField(null=True, verbose_name='Batafsil')),
                ('content_uz_Cyrl', models.TextField(null=True, verbose_name='Batafsil')),
                ('content_ru', models.TextField(null=True, verbose_name='Batafsil')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rish soni")),
                ('publish', models.BooleanField(default=True, verbose_name='Chop etish')),
                ('news_of_the_day', models.BooleanField(default=False, verbose_name='Kun yangiligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('to_send_bot', models.BooleanField(default=True, verbose_name='Telegram kanalga yuborish')),
                ('categories', models.ManyToManyField(to='main.category', verbose_name='Kategoriyalar')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region', verbose_name='Joy')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('intro', models.TextField(verbose_name='Kirish matni')),
                ('intro_en_us', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Latn', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Cyrl', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_ru', models.TextField(null=True, verbose_name='Kirish matni')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm')),
                ('url', models.URLField(verbose_name='Link')),
                ('to_send_bot', models.BooleanField(default=True, verbose_name='Telegram kanalga yuborish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('categories', models.ManyToManyField(to='main.category', verbose_name='Kategoriyalar')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
        migrations.CreateModel(
            name='BotMessageIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='Telegram Message Id')),
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article', verbose_name='Article')),
                ('video', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.video', verbose_name='Article')),
            ],
        ),
    ]
