# Generated by Django 5.0.2 on 2024-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_en_us', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_uz_Latn', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_uz_Cyrl', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('intro', models.TextField(verbose_name='Intro')),
                ('intro_en_us', models.TextField(null=True, verbose_name='Intro')),
                ('intro_uz_Latn', models.TextField(null=True, verbose_name='Intro')),
                ('intro_uz_Cyrl', models.TextField(null=True, verbose_name='Intro')),
                ('intro_ru', models.TextField(null=True, verbose_name='Intro')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en_us', models.TextField(null=True, verbose_name='Content')),
                ('content_uz_Latn', models.TextField(null=True, verbose_name='Content')),
                ('content_uz_Cyrl', models.TextField(null=True, verbose_name='Content')),
                ('content_ru', models.TextField(null=True, verbose_name='Content')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('categories', models.ManyToManyField(to='main.category', verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('intro', models.TextField(verbose_name='Intro')),
                ('intro_en_us', models.TextField(null=True, verbose_name='Intro')),
                ('intro_uz_Latn', models.TextField(null=True, verbose_name='Intro')),
                ('intro_uz_Cyrl', models.TextField(null=True, verbose_name='Intro')),
                ('intro_ru', models.TextField(null=True, verbose_name='Intro')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Cover Image')),
                ('url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('categories', models.ManyToManyField(to='main.category', verbose_name='Categories')),
            ],
        ),
    ]
