# Generated by Django 5.0.2 on 2024-09-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('url', models.URLField(verbose_name='Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('title_en_us', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('title_uz_Latn', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('title_uz_Cyrl', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('name_en_us', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_uz_Latn', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_uz_Cyrl', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Joy',
                'verbose_name_plural': 'Joylar',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Rasm')),
                ('intro', models.TextField(verbose_name='Kirish matni')),
                ('intro_en_us', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Latn', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Cyrl', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_ru', models.TextField(null=True, verbose_name='Kirish matni')),
                ('content', models.TextField(verbose_name='Batafsil')),
                ('content_en_us', models.TextField(null=True, verbose_name='Batafsil')),
                ('content_uz_Latn', models.TextField(null=True, verbose_name='Batafsil')),
                ('content_uz_Cyrl', models.TextField(null=True, verbose_name='Batafsil')),
                ('content_ru', models.TextField(null=True, verbose_name='Batafsil')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rish soni")),
                ('publish', models.BooleanField(default=True, verbose_name='Chop etish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('categories', models.ManyToManyField(to='main.category', verbose_name='Kategoriyalar')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_en_us', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Latn', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_uz_Cyrl', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('intro', models.TextField(verbose_name='Kirish matni')),
                ('intro_en_us', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Latn', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_uz_Cyrl', models.TextField(null=True, verbose_name='Kirish matni')),
                ('intro_ru', models.TextField(null=True, verbose_name='Kirish matni')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm')),
                ('url', models.URLField(verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('categories', models.ManyToManyField(to='main.category', verbose_name='Kategoriyalar')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
