# Generated by Django 5.0.2 on 2024-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video_content_video_video_alter_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content_en_us',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_uz_Cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AddField(
            model_name='video',
            name='content_uz_Latn',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
    ]
