# Generated by Django 5.0.2 on 2024-09-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_news_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_of_the_day',
            field=models.BooleanField(default=False, verbose_name='Kun yangiligi'),
        ),
    ]
