# Generated by Django 5.0.2 on 2024-11-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_news_of_the_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familya')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Rasm')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('licence_no', models.SmallIntegerField(blank=True, null=True, verbose_name='Guvohnoma raqami')),
            ],
            options={
                'verbose_name': 'Jamoa',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
    ]
