# Generated by Django 5.0.2 on 2024-12-01 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_content_alter_article_content_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en_us',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_uz_Cyrl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_uz_Latn',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=ckeditor.fields.RichTextField(verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_en_us',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_uz_Cyrl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_uz_Latn',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_en_us',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_uz_Cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_uz_Latn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro',
            field=ckeditor.fields.RichTextField(verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_en_us',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_uz_Cyrl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_uz_Latn',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kirish matni'),
        ),
    ]
