# Generated by Django 5.0.2 on 2024-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Hodim ', 'verbose_name_plural': 'Hodimlar'},
        ),
        migrations.AddField(
            model_name='article',
            name='message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name="Qo'shilgan sana"),
        ),
    ]
