# Generated by Django 5.0.2 on 2024-12-06 10:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_content_alter_article_content_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_uz_Cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_uz_Latn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_uz_Cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_uz_Latn',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Batafsil'),
        ),
    ]
