# Generated by Django 5.0.2 on 2024-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_article_content_alter_article_content_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_en_us',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_ru',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_uz_Cyrl',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_uz_Latn',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro',
            field=models.TextField(verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_en_us',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_ru',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_uz_Cyrl',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro_uz_Latn',
            field=models.TextField(null=True, verbose_name='Kirish matni'),
        ),
    ]
